# Generated by Django 4.1.13 on 2026-02-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election_model',
            name='tweet',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='election_prediction_model',
            name='tweet',
            field=models.CharField(max_length=3000),
        ),
    ]
